sudo: required
services:
  - docker

before_install:
  - docker build -t clarencetso2/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true clarencetso2/react-test npm test

after_success:
  - docker build -t clarencetso2/multi-client ./client
  - docker build -t clarencetso2/multi-nginx ./nginx
  - docker build -t clarencetso2/multi-server ./server
  - docker build -t clarencetso2/multi-worker ./worker
  #Log into docker CLI via travis environment variables
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #take images and push to docker hub
  - docker push clarencetso2/multi-client
  - docker push clarencetso2/multi-nginx
  - docker push clarencetso2/multi-server
  - docker push clarencetso2/multi-worker
