sudo: required
services:
  - docker

before_install:
  - docker build -t ctso2/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ctso2/react-test npm test

after_success:
  - docker build -t ctso2/multi-client ./client
  - docker build -t ctso2/multi-nginx ./nginx
  - docker build -t ctso2/multi-server ./server
  - docker build -t ctso2/multi-worker ./worker
  #Log into docker CLI via travis environment variables
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #take images and push to docker hub
  - docker push ctso2/multi-client
  - docker push ctso2/multi-nginx
  - docker push ctso2/multi-server
  - docker push ctso2/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  bucket_name: elasticbeanstalk-us-east-2-604389414674
  bucket_path: docker-multi
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
